language: python
python:
  - "3.4"
  - "3.5"
  - "nightly"

before_install:
  - export DJANGO_SETTINGS_MODULE=prototype.settings.production

# command to install dependencies
install: 
  - "pip install -r requirements.txt"

script: 
  - python manage.py test